### ISSUE TITLE
Assignment 2: Task1

### ISSUE THREAD

**Issue by I-am-sayantan** [I-am-sayantan/OPEN-SOFT-2022-PRE-PS-PHASE#28]
Image Processing (using OpenCV)

- From the provided [sudoku board images](https://github.com/I-am-sayantan/OPEN-SOFT-2022-PRE-PS-PHASE/tree/dev/sudoku%20board%20images) extract the 9x9 grid that represents the puzzle with values in their correct positions, try to do it with as manual editing as possible.
- Please make a .py/.ipynb file and make your PR inside the **dev branch** only.

**Comment by s-kaivalya** [comment]
I want to work on it!

**Comment by dhruvarya45** [comment]
I want to work on it.

**Comment by I-am-sayantan** [comment]
> I want to work on it!

Sure go ahead

**Comment by I-am-sayantan** [comment]
> I want to work on it.
> 
> 

Sure go ahead

**Comment by Nishant467** [comment]
I want to work on it.

**Comment by sarthak-nik** [comment]
I want to work on it.
